### ISSUE TITLE
cmd error

### ISSUE THREAD

**Issue by hellobiek** [semlanik/qtprotobuf-ci#1]
cmd should be: /qt-opensource-linux-x64-5.13.2.run --platform minimal --script /qt_installer.qs
in your Dockerfile

**Comment by semlanik** [comment]
Hi @hellobiek, if you mean "--platform" "-platform" it's correct. Please look at https://doc.qt.io/qt-5/embedded-linux.html. Didn't find better resource for command line options for qt, but either QT_QPA_PLATFORM or -platform specifies QPA.

**Comment by hellobiek** [comment]
you should not just see the doc, just run it in real env.

**Comment by semlanik** [comment]
Hi @hellobiek, not sure what does mean "real env", but this procedure works successfully. There is warning in logs, but it happens because there are two layers where command line arguments are processed:

1. QApplication it self when you pass argc/argv to it's constructor.
2. Somewhere in Qt Installer Framework code

For first case it selects correct QPA that is required to run qt application without graphical subsystem presence

For second case it processed by "userspace" code of Qt Installer Framework and is not recognized as known option. So we may ignore this warning at all.

Simply like this. Hope this information was helpful.

**Comment by hellobiek** [comment]
OK, when I built this image locally, the warnings make me confused. 

Thank You!
